config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  get 'errors/show'
  get 'errors/unauthorized'
  root to: 'home#welcome'
  get '/events/:event_code', to: 'home#index', as: :home
  get '/events/:event_code/thank_you', to: 'home#thank_you', as: :thank_you
  get '/events/:event_code/denied', to: 'home#denied', as: :denied
  get '/events/:event_code/disabled', to: 'home#disabled', as: :disabled
  get '/find_event', to: 'home#find_event', as: :find_event
  get '/profile', to: 'home#profile', as: :profile
  put '/profile', to: 'home#update_profile', as: :update_profile
  get '/forgot_password', to: 'home#forgot_password', as: :forgot_password
  post '/reset_password', to: 'home#reset_password', as: :reset_password
  get '/contact_us', to: 'home#contact_us', as: :contact_us
  get '/about_us', to: 'home#about_us', as: :about_us

  scope 'admins' do
    get '/forgot_password', to: 'admins#forgot_password', as: :admin_forgot_password
    post '/forgot_password', to: 'admins#reset_forgot_password', as: :admin_reset_password
    get '/dashboard', to: 'admins#dashboard', as: :admin_dashboard
    resources :events, except: [:new, :edit] do
      put :upload_brochure, to: 'events#upload_brochure', on: :member
      get :launch, to: 'events#launch', on: :member
      get :expo, to: 'events#expo', on: :member

      resources :guest_lists do
        post :set_status, on: :collection
        post :set_raffle_status, on: :collection
        get :reset_raffle_statuses, on: :collection
        get :download_csv, on: :collection
      end
      resources :raffles, except: [:index]
      resources :questionnaires, except: [:index] do
        get '/pinned/:answer_id', to: 'questionnaires#pinned', on: :member, as: :pinned_answer
      end
      resources :feed_backs, except: [:index] do
        get :download_csv, on: :member
      end
    end
    resources :admins do
      post :create_admin_events, on: :member
      delete :destroy_admin_events, on: :member
      put :reset_password, on: :member
      get :profile, on: :collection
      put :profile, to: 'admins#update_profile', on: :collection
      get :change_password, on: :collection
      put :change_password, to: 'admins#update_password', on: :collection
    end
    resources :users, except: [:new, :edit, :create, :update, :destroy] do
      put :reset_password, on: :member
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :reactions, only: [:create] do
        delete :destroy, on: :collection
      end
      resources :chats, only: [:index, :create]
      resources :announcements, only: [:index, :create, :update]
      get '/fetch_current_user', to: 'users#fetch_current_user', as: :fetch_current_user
      resources :events, only: [:show, :update]
      resources :raffles, only: [:index, :show, :update]
      resources :questionnaires, only: [:update]
      resources :guest_lists, only: [:index, :show]
      resources :answers, only: [:create]
      get '/fetch_current_event/:id', to: 'events#fetch_current_event', as: :fetch_current_event

      resources :game_scores, only: [:create, :index, :show, :update]
      resources :users, only: [:show]
      resources :ratings, only: [:index, :create]
    end
  end

  # devise_for :users, skip: [:sessions]
  # as :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   post 'sign_in', to: 'devise/sessions#create'
  #   get 'sign_out', to: 'devise/sessions#destroy'
  #   #root to: 'devise/sessions#new', as: 'authenticated_user_root'
  # end
  devise_for :admins, controllers: { sessions: 'admins/sessions' }, :skip => [:registrations]
    as :admin do
    get 'admins/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'admins/registrations#update', :as => 'admin_registration'
  end
  # devise_for :employees, path: 'dashboard/employees', skip: [:sessions]
  # as :employee do
  #   get 'login', to: 'devise/sessions#new', as: :new_app_account_session
  #   post 'login', to: 'devise/sessions#create', as: :app_account_session
  #   get 'logout', to: 'devise/sessions#destroy', as: :destroy_app_account_session
  #   root to: 'devise/sessions#new'
  # end

  devise_for :users, skip: [:sessions, :registrations]
  as :user do
    get '/events/:event_code/sign_in', to: 'users/sessions#new', as: :new_user_session
    post '/events/:event_code/sign_in', to: 'users/sessions#create', as: :user_session
    get 'sign_out', to: 'users/sessions#destroy', as: :destroy_user_session

    get 'users/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get '/events/:event_code/sign_up', to: 'users/registrations#new', as: :new_user_registration
    get 'users/edit', to: 'users/registrations#edit', as: :edit_user_registration
    patch 'users', to: 'users/registrations#update', as: :user_registration_patch
    put 'users', to: 'users/registrations#update', as: :user_registration_put
    delete 'users', to: 'users/registrations#destroy', as: :user_registration_delete
    post '/events/:event_code/users', to: 'users/registrations#create', as: :user_registration
  end
  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # %w( 404 422 500 503 ).each do |code|
  #   match code, to: "errors#show", code: code
  # end
  get '/unauthorized', to: "errors#unauthorized"
  mount ActionCable.server => '/cable'
end

app/views/admins/dashboard.html.erb
<%= render partial: "layouts/shared/breadcrumbs", locals: {
  links: [],
  current_path: "Dashboard"
} %>

<div class="container content-wrapper">
  <%= render partial: "layouts/shared/success_messages", locals: { messages: flash[:notice] } %>
  <%= render partial: "layouts/shared/alert_messages", locals: { messages: flash[:alert] } %>
  <div class="row text-end mb-3">
    <div class="col-6">
      <!-- events status https://chartkick.com/ -->
      <%= pie_chart Event.group(:status).count, title: "Events Status" %>
    </div>
    <div class="col-6">
      <!-- count events -->
      <%= column_chart Event.group(:start_date).count, title: "Number of Events" %>
    </div>
  </div>

</div>

app/views/admins/edit.html.erb
<%= render partial: "layouts/shared/breadcrumbs", locals: {
  links: [
    { path: admins_path, path_name: "Admins" },
    { path: admin_path(@admin), path_name: "#{@admin.id}" }
  ],
  current_path: "Edit"
} %>
<div class="container content-wrapper">
  <div class="row mb-3">
    <div class="col-12 text-start">
      <h2 class="event_title">Edit Admin</h2>
    </div>
    <hr/>
  </div>
    <%= form_for @admin, as: :admin, url: admin_path(@admin), method: :put, html: { class: "", multipart: true } do |f| %>
      <%= render partial: "layouts/shared/success_messages", locals: { messages: flash[:notice] } %>
      <%= render partial: "layouts/shared/error_messages", locals: { messages: @admin.errors.full_messages } %>
      <%= render partial: "admins/shared/form", locals: {f: f, with_password: false} %>
      <div class="row">
        <div class="col-12 text-end">
          <%= submit_tag "Edit Admin", class: "btn btn-submit" %>
        </div>
      </div>
    <% end %>
</div>

app/views/admins/forgot_password.html.erb
<div class="chat-live-wrapper thankyou main-bg" style="">
  <div class="container px-5 py-3">
      <div class="row">
            <div class="col-12">
               <%= form_for @admin, as: :admin, url: admin_reset_password_path, method: :post, html: { class: "row password-form-wrapper text-start" } do |f| %>
               <%= render partial: "layouts/shared/error_messages", locals: { messages: @admin.errors.full_messages } %>
                  <% if notice %>
                     <p class="alert alert-success"><%= notice %></p>
                  <% end %>
                  <% if alert %>
                     <p class="alert alert-danger"><%= alert %></p>
                  <% end %>
                  <div class="row px-0">
                    <div class="col">
                      <h4 class="text-start">Forgot Password?</h4>
                      <hr/>
                    </div>
                  </div>
                  <div class="mb-3 px-0">
                     <%= f.label :email %><br />
                     <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
                  </div>
                  <div class="actions text-center">
                     <%= f.submit "Update", class: "btn btn-blue" %>
                  </div>
                  <% end %>
            </div>
      </div>
  </div>
</div>

app/views/admins/index.html.erb
<%= render partial: "layouts/shared/breadcrumbs", locals: {
  links: [],
  current_path: "Admins"
} %>

<div class="container content-wrapper">
  <%= render partial: "layouts/shared/success_messages", locals: { messages: flash[:notice] } %>
  <%= render partial: "layouts/shared/alert_messages", locals: { messages: flash[:alert] } %>
  <div class="row text-end mb-3">
    <div class="col col-lg-12">
      <% if can? :create, Admin %>
        <%= link_to "Create Admin", new_admin_path, class: "btn btn-edit btn-blue" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col col-lg-12">
      <table id="admin_list" class="table user-data-table hover">
        <thead>
          <tr>
            <th>Full Name</th>
            <th>Email Address</th>
            <th>Reset Password?</th>
            <th>Role</th>
            <th>Temporary Password</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @admins.each do |admin| %>
            <tr>
              <td><%= admin.full_name %></td>
              <td><%= admin.email %></td>
              <td><%= admin.reset_password %></td>
              <td><%= admin.role_name %></td>
              <td><%= admin.temporary_password %></td>
              <td>
                <% if can? :edit, Admin %>
                  <%= form_for admin, as: :admin, url: reset_password_admin_path(admin), method: :put, html: { class: "", multipart: true } do |f| %>
                    <%= submit_tag "Reset Password", class: "btn btn-reset" %>
                  <% end %>
                <% end %>
              </td>
              <td class="actions">

                <% if can? :show, Admin %>
                  <%= link_to "Show", admin_path(admin), class: 'btn btn-view' %>
                <% end %>

                <% if can? :update, Admin %>
                <%= link_to "Edit", edit_admin_path(admin), class: 'btn btn-edit' %>
                <% end %>

                <% if can? :destroy, Admin %>
                <a class="btn btn-remove" href="#" data-bs-toggle="modal" data-bs-target="#delete-modal-id-<%= admin.id %>">Delete</a>
                <%= render partial: "layouts/shared/delete_modal", locals: { index_id: "#{admin.id}", m_name: "Admin", name: admin.full_name, path: admin_path(admin) } %>
                <% end %>

              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/new.html.erb
<%= render partial: "layouts/shared/breadcrumbs", locals: {
  links: [{ path: admins_path, path_name: "Admins" }],
  current_path: "New"
} %>
<div class="container content-wrapper">
  <div class="row mb-3">
    <div class="col-12 text-start">
      <h4>Details</h4>
    </div>
    <hr/>
  </div>
    <%= form_for @admin, as: :admin, url: admins_path(@admin), method: :post, html: { class: "" } do |f| %>
      <%= render partial: "layouts/shared/success_messages", locals: { messages: flash[:notice] } %>
      <%= render partial: "layouts/shared/error_messages", locals: { messages: @admin.errors.full_messages } %>
      <%= render partial: "admins/shared/form", locals: {f: f, with_password: true} %>
      <div class="row">
        <div class="col-12 text-center">
          <%= submit_tag "Create Admin", class: "btn btn-submit" %>
        </div>
      </div>
    <% end %>
</div>

app/views/admins/profile.html.erb
<%= render partial: "layouts/shared/breadcrumbs", locals: {
  links: [],
  current_path: "My Profile"
} %>
<div class="container content-wrapper">
    <div class="row text-end mb-3">
    <div class="col col-lg-12">
        <div class="heading-wrapper">
            <h4 class="text-start">My Profile</h4>
            <hr/>
        </div>
        <%= form_for @admin, as: :admin, url: profile_admins_path, method: :put, html: { class: "profile-form-wrapper text-start", multipart: true } do |f| %>
          <%= render partial: "layouts/shared/success_messages", locals: { messages: flash[:notice] } %>
          <%= render partial: "layouts/shared/error_messages", locals: { messages: @admin.errors.full_messages } %>
          <div class="mb-3 px-0">
              <label for="name">Name</label>
              <%= f.text_field :full_name, class: 'form-control', id: "full_name" %>
          </div>
          <div class="mb-3 px-0">
              <label for="email">Email Address</label>
              <%= f.email_field :email, class: 'form-control', id: "email" %>
          </div>
          <div class="mb-3 px-0">
              <label for="adminMemberType">Company</label>
              <%= f.text_field :company, class: "form-control" %>
          </div>
          <div class="mb-3 px-0">
              <label for="adminMemberID">Position</label>
              <%= f.text_field :position, class: "form-control" %>
          </div>
          <div class="mb-3 px-0">
              <label for="affiliation">Contact Number</label>
              <%= f.text_field :contact_number, class: "form-control" %>
          </div>
          <div class="mb-3 px-0 text-center">
            <%= link_to "CLICK HERE TO CHANGE PASSWORD", edit_admin_registration_path, class: "password__label" %>
          </div>

          <div class="py-3 text-center">
              <%= submit_tag "Save", class: "btn btn-blue px-5" %>
          </div>
        <% end %>
    </div>
    </div>
</div>

app/views/admins/show.html.erb
<%= render partial: "layouts/shared/breadcrumbs", locals: {
  links: [{ path: admins_path, path_name: "Admins" }],
  current_path: "#{@admin.id}"
} %>
<div class="container content-wrapper">
   <%= render partial: "layouts/shared/success_messages", locals: { messages: flash[:notice] } %>
   <%= render partial: "layouts/shared/alert_messages", locals: { messages: flash[:alert] } %>
   <div class="row">
      <div class="col-12 text-start">
         <h2 class="admin_title"><%= @admin.full_name %></h2>
      </div>
   </div>
   <div class="row text-start mb-3 mx-3">
      <div class="col col-lg-4">
         <div class="admin_wrapper">
            <span class="mr-3"><strong>Email Address:</strong></span><br>
            <span class="admin_detail"><%= @admin.email %></span>
         </div>
      </div>
      <div class="col col-lg-4">
         <div class="admin_wrapper">
            <span class="mr-3"><strong>Company:</strong></span><br>
            <span class="admin_detail"><%= @admin.company %></span>
         </div>
      </div>
   </div>
   <div class="row text-start mb-3 mx-3">
      <div class="col col-lg-4">
         <div class="admin_wrapper">
            <span class="mr-3"><strong>Position:</strong></span><br>
            <span class="admin_detail"><%= @admin.position %></span>
         </div>
      </div>
      <div class="col col-lg-4">
         <div class="admin_wrapper">
            <span class="mr-3"><strong>Contact Number:</strong></span><br>
            <span class="admin_detail"><%= @admin.contact_number %></span>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col col-lg-12">
         <hr/>
      </div>
   </div>
   <div class="row">
      <div class="col col-lg-12">
         <div class="tab-pane fade show active" id="nav-events" role="tabpanel" aria-labelledby="nav-events-tab">
            <% if can? :manage, Admin %>
            <div class="row text-end">
               <div class="col-12">
                  <button type="button" class="btn btn-blue my-3 " data-bs-toggle="modal" data-bs-target="#adminAddEvent">
                  Add Event
                  </button>
               </div>
            </div>
            <div class="modal fade" id="adminAddEvent" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="adminAddEvent" aria-hidden="true">
               <div class="modal-dialog modal-md">
                  <div class="modal-content">
                     <div class="modal-header">
                        <h5 class="modal-title" id="adminAddEvent">Add Event to Manage</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                     </div>
                     <div class="modal-body my-3">
                        <div class="container">
                           <div class="row">
                              <div class="col col-lg-12">
                                 <%= form_for @admin_event, as: :admin_event, url: create_admin_events_admin_path(id: @admin.id), method: :post, html: { class: "" } do |f| %>
                                 <div class="mb-3">
                                    <div class="row">
                                       <div class="col col-lg-12">
                                          <label for="event">Event</label>
                                          <%= f.hidden_field :admin_id, value: @admin.id %>
                                          <%= f.collection_select :event_id, @events, :id, :title, {}, { class: 'form-select' } %>
                                       </div>
                                    </div>
                                 </div>
                                 <div class="row">
                                    <div class="col-12 text-end">
                                       <%= submit_tag "Add Event", class: "btn btn-submit" %>
                                    </div>
                                 </div>
                                 <% end %>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <% end %>
            <table id="event_list_table" class="table data-table hover">
               <thead>
                  <tr>
                     <th>Event Title</th>
                     <th>Event Code</th>
                     <th>Event Type</th>
                     <th>Event Date</th>
                     <th></th>
                  </tr>
               </thead>
               <tbody>
                  <% @admin_events.each do |admin_event| %>
                  <tr>
                     <td><%= admin_event.event.title %></td>
                     <td><%= admin_event.event.event_code %></td>
                     <td><%= admin_event.event.event_type_name %></td>
                     <td>
                        <%= date_formatter(admin_event.event.start_date) %>
                        <% unless (admin_event.event.start_date.nil? || admin_event.event.end_date.nil?) %>
                        -
                        <% end %>
                        <%= date_formatter(admin_event.event.end_date) %>
                     </td>
                     <td class="actions">
                        <% if can? :manage, Admin %>
                        <a class="btn btn-remove" href="#" data-bs-toggle="modal" data-bs-target="#delete-modal-id-<%= admin_event.id %>">Delete</a>
                        <%= render partial: "layouts/shared/delete_modal", locals: { index_id: "#{admin_event.id}", m_name: "Admin Event", name: admin_event.event.title, path: destroy_admin_events_admin_path(id: @admin.id, admin_event_id: admin_event.id) } %>
                        <% end %>
                     </td>
                  </tr>
                  <% end %>
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>