config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  get 'errors/show'
  get 'errors/unauthorized'
  root to: 'home#welcome'
  get '/events/:event_code', to: 'home#index', as: :home
  get '/events/:event_code/thank_you', to: 'home#thank_you', as: :thank_you
  get '/events/:event_code/denied', to: 'home#denied', as: :denied
  get '/events/:event_code/disabled', to: 'home#disabled', as: :disabled
  get '/find_event', to: 'home#find_event', as: :find_event
  get '/profile', to: 'home#profile', as: :profile
  put '/profile', to: 'home#update_profile', as: :update_profile
  get '/forgot_password', to: 'home#forgot_password', as: :forgot_password
  post '/reset_password', to: 'home#reset_password', as: :reset_password
  get '/contact_us', to: 'home#contact_us', as: :contact_us
  get '/about_us', to: 'home#about_us', as: :about_us

  scope 'admins' do
    get '/forgot_password', to: 'admins#forgot_password', as: :admin_forgot_password
    post '/forgot_password', to: 'admins#reset_forgot_password', as: :admin_reset_password
    get '/dashboard', to: 'admins#dashboard', as: :admin_dashboard
    resources :events, except: [:new, :edit] do
      put :upload_brochure, to: 'events#upload_brochure', on: :member
      get :launch, to: 'events#launch', on: :member
      get :expo, to: 'events#expo', on: :member

      resources :guest_lists do
        post :set_status, on: :collection
        post :set_raffle_status, on: :collection
        get :reset_raffle_statuses, on: :collection
        get :download_csv, on: :collection
      end
      resources :raffles, except: [:index]
      resources :questionnaires, except: [:index] do
        get '/pinned/:answer_id', to: 'questionnaires#pinned', on: :member, as: :pinned_answer
      end
      resources :feed_backs, except: [:index] do
        get :download_csv, on: :member
      end
    end
    resources :admins do
      post :create_admin_events, on: :member
      delete :destroy_admin_events, on: :member
      put :reset_password, on: :member
      get :profile, on: :collection
      put :profile, to: 'admins#update_profile', on: :collection
      get :change_password, on: :collection
      put :change_password, to: 'admins#update_password', on: :collection
    end
    resources :users, except: [:new, :edit, :create, :update, :destroy] do
      put :reset_password, on: :member
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :reactions, only: [:create] do
        delete :destroy, on: :collection
      end
      resources :chats, only: [:index, :create]
      resources :announcements, only: [:index, :create, :update]
      get '/fetch_current_user', to: 'users#fetch_current_user', as: :fetch_current_user
      resources :events, only: [:show, :update]
      resources :raffles, only: [:index, :show, :update]
      resources :questionnaires, only: [:update]
      resources :guest_lists, only: [:index, :show]
      resources :answers, only: [:create]
      get '/fetch_current_event/:id', to: 'events#fetch_current_event', as: :fetch_current_event

      resources :game_scores, only: [:create, :index, :show, :update]
      resources :users, only: [:show]
      resources :ratings, only: [:index, :create]
    end
  end

  # devise_for :users, skip: [:sessions]
  # as :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   post 'sign_in', to: 'devise/sessions#create'
  #   get 'sign_out', to: 'devise/sessions#destroy'
  #   #root to: 'devise/sessions#new', as: 'authenticated_user_root'
  # end
  devise_for :admins, controllers: { sessions: 'admins/sessions' }, :skip => [:registrations]
    as :admin do
    get 'admins/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'admins/registrations#update', :as => 'admin_registration'
  end
  # devise_for :employees, path: 'dashboard/employees', skip: [:sessions]
  # as :employee do
  #   get 'login', to: 'devise/sessions#new', as: :new_app_account_session
  #   post 'login', to: 'devise/sessions#create', as: :app_account_session
  #   get 'logout', to: 'devise/sessions#destroy', as: :destroy_app_account_session
  #   root to: 'devise/sessions#new'
  # end

  devise_for :users, skip: [:sessions, :registrations]
  as :user do
    get '/events/:event_code/sign_in', to: 'users/sessions#new', as: :new_user_session
    post '/events/:event_code/sign_in', to: 'users/sessions#create', as: :user_session
    get 'sign_out', to: 'users/sessions#destroy', as: :destroy_user_session

    get 'users/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get '/events/:event_code/sign_up', to: 'users/registrations#new', as: :new_user_registration
    get 'users/edit', to: 'users/registrations#edit', as: :edit_user_registration
    patch 'users', to: 'users/registrations#update', as: :user_registration_patch
    put 'users', to: 'users/registrations#update', as: :user_registration_put
    delete 'users', to: 'users/registrations#destroy', as: :user_registration_delete
    post '/events/:event_code/users', to: 'users/registrations#create', as: :user_registration
  end
  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # %w( 404 422 500 503 ).each do |code|
  #   match code, to: "errors#show", code: code
  # end
  get '/unauthorized', to: "errors#unauthorized"
  mount ActionCable.server => '/cable'
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::ApplicationController

  before_action :doorkeeper_authorize!, only: [:show]
  before_action :set_user, only: [:show]

  def fetch_current_user
    render json: @current_user, serializer: UserSerializer
  end

  def show
    render json: @user
  end

  private

  def set_user
    @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      render json: { errors: e.to_s }, status: :not_found
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'main', only: [:edit, :update]
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action -> { check_event_code params[:event_code] }, only: [:new, :create, :edit, :update]

  # GET /resource/sign_up
  def new
    if @event.nil?
      redirect_to root_path, alert: "Invalid Event Code!"
    elsif @event.queued?
      redirect_to root_path, alert: "Event not yet started!"
    elsif @event.done?
      redirect_to root_path, alert: "Event already done!"
    else
      build_resource
      yield resource if block_given?
      respond_with resource
    end
  end

  # POST /resource
  def create
    if @event.nil?
      redirect_to root_path, alert: "Invalid Event Code!"
    elsif @event.queued?
      redirect_to root_path, alert: "Event not yet started!"
    elsif @event.done?
      redirect_to root_path, alert: "Event already done!"
    else
     build_resource(sign_up_params)

     resource.save
     yield resource if block_given?
     if resource.persisted?
       if resource.active_for_authentication?
         GuestList.create_guest_list(resource, @event)
         set_flash_message! :notice, :signed_up
         sign_up(resource_name, resource)
         respond_with resource, location: after_sign_up_path_for(resource, @event)
       else
         set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
         expire_data_after_sign_in!
         respond_with resource, location: after_inactive_sign_up_path_for(resource)
       end
     else
       clean_up_passwords resource
       set_minimum_password_length
       respond_with resource
     end
   end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
    resource.reset_password = false
    resource.temporary_password = ""
    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

      respond_with resource, location: after_update_path_for(resource, @event)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params

    added_attrs = [:event_code, :email, :password, :password_confirmation, :contact_number,
      :full_name, :member_id, :member_type, :affiliation, :abo_number, :aes_number,
      :company, :id_number, :distributor_number, :employee_number, :mailing_address,
      :member_company, :upline, :who_invited_you, :abo_type, :distributor_type]

    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    update_attrs = [:password, :password_confirmation, :current_password]
    devise_parameter_sanitizer.permit :account_update, keys: update_attrs
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource, event)
    #super(resource)
    if event.has_expo?
      expo_path(event_code: event.event_code)
    else
      home_path(event_code: event.event_code)
    end
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource, event)
    flash[:notice] = "Changed Password succesfully"
    home_path(event_code: event.event_code)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  before_action -> { check_event_code params[:event_code] }, only: [:new, :create]

  # GET /resource/sign_in
  def new
    if @event.nil?
      redirect_to root_path, alert: "Invalid Event Code!"
    elsif @event.queued?
      redirect_to root_path, alert: "Event not yet started!"
    elsif @event.done?
      redirect_to root_path, alert: "Event already done!"
    else
      self.resource = resource_class.new(sign_in_params)
      clean_up_passwords(resource)
      yield resource if block_given?
      respond_with(resource, serialize_options(resource))
    end
  end

  # POST /resource/sign_in
  def create
    if @event.nil?
      redirect_to root_path, alert: "Invalid Event Code!"
    elsif @event.queued?
      redirect_to root_path, alert: "Event not yet started!"
    elsif @event.done?
      redirect_to root_path, alert: "Event already done!"
    else
      self.resource = warden.authenticate!(auth_options)
      GuestList.create_guest_list(resource, @event)
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource, @event)
    end

  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'admin'

  before_action :authenticate_admin!
  load_and_authorize_resource :user

  def index
    @users = if @current_user.admin?
      event_ids = @current_user.events.ids
      User.admin_users(event_ids)
    else
      @users
    end

    @users = @users.sorted
  end

  def show
  end

  def reset_password
    @user = @user.generate_temporary_password
    if @user.save
      redirect_to user_path(@user), notice: "User #{@user.full_name} reset password successfully!"
    else
      @users = if @current_user.admin?
        event_ids = @current_user.events.ids
        User.admin_users(event_ids)
      else
        @users
      end
      @users = @users.sorted
      render :index
    end
  end

  private

end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h6><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span><%= resource.errors.count %> <%= resource.errors.count > 1 ? "errors" : "error" %> prohibited this information from being saved:
    </h6>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/shared/_registration_new.html.erb
<div class="col-12 col-md-6 col-lg-6 registration-wrapper" style="background: <%= @event.session_background_color %>;">
    <h2>Create Account</h2>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: 'row text-center justify-content-start'}) do |f| %>
      <%= render "users/shared/error_messages", resource: resource %>
      <%= f.hidden_field :event_code, value: @event.event_code %>
      <div class="col col-lg-12">
          <label for="full_name">Full Name <span class="required">*</span></label>
          <%= f.text_field :full_name, autofocus: true, autocomplete: "email", class:"form-control"%>
      </div>
      <div class="col col-md-12">
          <label for="email">Email <span class="required">*</span></label>
          <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="col col-md-12 col-lg-6">
        <label for="passowrd">Password <span class="required">*</span></label>
        <%= f.password_field :password, autocomplete: "new-password", class:"form-control" %>
      </div>
      <div class="col col-md-12 col-lg-6">
          <label for="password_confirmation">Password Confirmation <span class="required">*</span></label>
          <%= f.password_field :password_confirmation, autocomplete: "new-password", class:"form-control" %>
      </div>
      <% if @event.include_affiliation? %>
        <div class="col col-md-6">
            <label for="email">
              Affiliation
              <% if @event.required_affiliation? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <%= f.text_field :affiliation, class: "form-control" %>
        </div>
      <% end %>
      <% if @event.include_company? %>
        <div class="col col-md-6">
            <label for="email">
              Company
              <% if @event.required_company? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <%= f.text_field :company, class: "form-control" %>
        </div>
      <% end %>
      <% if @event.include_member_company? %>
      <div class="col col-md-6">
          <label for="email">
            Member Company
            <% if @event.required_member_company? %>
              <span class="required">*</span>
            <% end %>
          </label>
          <%= f.text_field :member_company, class: "form-control" %>
      </div>
      <% end %>

      <% if @event.include_contact_number? %>
      <div class="col col-md-6">
          <label for="email">
            Contact Number
            <% if @event.required_contact_number? %>
              <span class="required">*</span>
            <% end %>
          </label>
          <%= f.text_field :contact_number, class: "form-control" %>
      </div>
      <% end %>
      <% if @event.include_mailing_address? %>
        <div class="col col-md-6">
            <label for="email">
              Mailing Address
              <% if @event.required_mailing_address? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <%= f.text_field :mailing_address, class: "form-control" %>
        </div>
      <% end %>
      <% if @event.include_who_invited_you? %>
        <div class="col col-md-6">
            <label for="email">
              Who Invited You?
              <% if @event.required_who_invited_you? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <%= f.text_field :who_invited_you, class: "form-control" %>
        </div>
      <% end %>
      <% if @event.include_upline? %>
        <div class="col col-md-6">
            <label for="email">
              Upline
              <% if @event.required_upline? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <%= f.text_field :upline, class: "form-control" %>
        </div>
      <% end %>

      <% if @event.include_member_type? %>
        <div class="col col-md-6">
            <label for="email">
              Member Type
              <% if @event.required_member_type? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <% if @event.with_guest_member_type %>
              <%= f.select :member_type, User::MEMBER_TYPES_WITH_GUEST.invert, {}, { class: 'form-select' } %>
            <% else %>
              <%= f.select :member_type, User::MEMBER_TYPES.invert, {}, { class: 'form-select' } %>
            <% end %>
        </div>
      <% end %>
      <% if @event.include_member_id? %>
        <div class="col col-md-6">
            <label for="email">
              Member Id
              <% if @event.required_member_id? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <%= f.text_field :member_id, class: "form-control" %>
        </div>
      <% end %>
      <% if @event.include_abo_type? %>
        <div class="col col-md-6">
            <label for="email">
              ABO Type
              <% if @event.required_abo_type? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <% if @event.with_guest_abo_type %>
              <%= f.select :abo_type, User::ABO_TYPES_WITH_GUEST.invert, {}, { class: 'form-select' } %>
            <% else %>
              <%= f.select :abo_type, User::ABO_TYPES.invert, {}, { class: 'form-select' } %>
            <% end %>
        </div>
      <% end %>
      <% if @event.include_abo_number? %>
        <div class="col col-md-6">
            <label for="email">
              ABO Number
              <% if @event.required_abo_number? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <%= f.text_field :abo_number, class: "form-control" %>
        </div>
      <% end %>
      <% if @event.include_aes_number? %>
        <div class="col col-md-6">
            <label for="email">
              AES Number
              <% if @event.required_aes_number? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <%= f.text_field :aes_number, class: "form-control" %>
        </div>
      <% end %>
      <% if @event.include_distributor_type? %>
        <div class="col col-md-6">
            <label for="email">
              Distributor Type
              <% if @event.required_distributor_type? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <% if @event.with_guest_distributor_type %>
              <%= f.select :distributor_type, User::DISTRIBUTOR_TYPES_WTIH_GUEST.invert, {}, { class: 'form-select' } %>
            <% else %>
              <%= f.select :distributor_type, User::DISTRIBUTOR_TYPES.invert, {}, { class: 'form-select' } %>
            <% end %>
        </div>
      <% end %>
      <% if @event.include_distributor_number? %>
        <div class="col col-md-6">
            <label for="email">
              Distributor Number
              <% if @event.required_distributor_number? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <%= f.text_field :distributor_number, class: "form-control" %>
        </div>
      <% end %>
      <% if @event.include_employee_number? %>
        <div class="col col-md-6">
            <label for="email">
              Employee Number
              <% if @event.required_employee_number? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <%= f.text_field :employee_number, class: "form-control" %>
        </div>
      <% end %>
      <% if @event.include_id_number? %>
        <div class="col col-md-6">
            <label for="email">
              Id Number
              <% if @event.required_id_number? %>
                <span class="required">*</span>
              <% end %>
            </label>
            <%= f.text_field :id_number, class: "form-control" %>
        </div>
      <% end %>

      <div class="row mt-3">
        <div class="col-12">
          <%= f.submit "Sign up", class:"btn btn-sign-up w-100", style: "background: #{@event.session_mouse_out};", onmouseover:"this.style.background='#{@event.session_mouse_over}'", onmouseout:"this.style.background='#{@event.session_mouse_out}'" %>
        </div>
      </div>
    <% end %>
</div>

app/views/users/shared/_session_new.html.erb
<div class="col-12 col-md-6 col-lg-6 px-5 py-3 img-wrapper">
    <h2 style="color: <%= "#{@event.session_mouse_out}"%>">Login</h2>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: 'login-user text-center'} ) do |f| %>
      <div class="mb-3">
        <%= f.label :email, style: "color: #{@event.session_mouse_out};" %><br />
        <%= f.email_field :email, class: "form-control", autofocus: true, autocomplete: "email" %>
      </div>

      <div class="mb-3">
        <%= f.label :password, style: "color: #{@event.session_mouse_out};" %><br />
        <%= f.password_field :password, class: "form-control", autocomplete: "current-password" %>
      </div>

      <div class="mb-3 forgot-password">
        <%= link_to "Forgot your password?", forgot_password_path %>
      </div>

      <div class="actions">
        <%= f.submit "Sign in", class:"btn btn-sign-in", style: "background: #{@event.session_mouse_out};", onmouseover:"this.style.background='#{@event.session_mouse_over}'", onmouseout:"this.style.background='#{@event.session_mouse_out}'" %>
      </div>
    <% end %>
</div>