config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  get 'errors/show'
  get 'errors/unauthorized'
  root to: 'home#welcome'
  get '/events/:event_code', to: 'home#index', as: :home
  get '/events/:event_code/thank_you', to: 'home#thank_you', as: :thank_you
  get '/events/:event_code/denied', to: 'home#denied', as: :denied
  get '/events/:event_code/disabled', to: 'home#disabled', as: :disabled
  get '/find_event', to: 'home#find_event', as: :find_event
  get '/profile', to: 'home#profile', as: :profile
  put '/profile', to: 'home#update_profile', as: :update_profile
  get '/forgot_password', to: 'home#forgot_password', as: :forgot_password
  post '/reset_password', to: 'home#reset_password', as: :reset_password
  get '/contact_us', to: 'home#contact_us', as: :contact_us
  get '/about_us', to: 'home#about_us', as: :about_us

  scope 'admins' do
    get '/forgot_password', to: 'admins#forgot_password', as: :admin_forgot_password
    post '/forgot_password', to: 'admins#reset_forgot_password', as: :admin_reset_password
    get '/dashboard', to: 'admins#dashboard', as: :admin_dashboard
    resources :events, except: [:new, :edit] do
      put :upload_brochure, to: 'events#upload_brochure', on: :member
      get :launch, to: 'events#launch', on: :member
      get :expo, to: 'events#expo', on: :member

      resources :guest_lists do
        post :set_status, on: :collection
        post :set_raffle_status, on: :collection
        get :reset_raffle_statuses, on: :collection
        get :download_csv, on: :collection
      end
      resources :raffles, except: [:index]
      resources :questionnaires, except: [:index] do
        get '/pinned/:answer_id', to: 'questionnaires#pinned', on: :member, as: :pinned_answer
      end
      resources :feed_backs, except: [:index] do
        get :download_csv, on: :member
      end
    end
    resources :admins do
      post :create_admin_events, on: :member
      delete :destroy_admin_events, on: :member
      put :reset_password, on: :member
      get :profile, on: :collection
      put :profile, to: 'admins#update_profile', on: :collection
      get :change_password, on: :collection
      put :change_password, to: 'admins#update_password', on: :collection
    end
    resources :users, except: [:new, :edit, :create, :update, :destroy] do
      put :reset_password, on: :member
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :reactions, only: [:create] do
        delete :destroy, on: :collection
      end
      resources :chats, only: [:index, :create]
      resources :announcements, only: [:index, :create, :update]
      get '/fetch_current_user', to: 'users#fetch_current_user', as: :fetch_current_user
      resources :events, only: [:show, :update]
      resources :raffles, only: [:index, :show, :update]
      resources :questionnaires, only: [:update]
      resources :guest_lists, only: [:index, :show]
      resources :answers, only: [:create]
      get '/fetch_current_event/:id', to: 'events#fetch_current_event', as: :fetch_current_event

      resources :game_scores, only: [:create, :index, :show, :update]
      resources :users, only: [:show]
      resources :ratings, only: [:index, :create]
    end
  end

  # devise_for :users, skip: [:sessions]
  # as :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   post 'sign_in', to: 'devise/sessions#create'
  #   get 'sign_out', to: 'devise/sessions#destroy'
  #   #root to: 'devise/sessions#new', as: 'authenticated_user_root'
  # end
  devise_for :admins, controllers: { sessions: 'admins/sessions' }, :skip => [:registrations]
    as :admin do
    get 'admins/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'admins/registrations#update', :as => 'admin_registration'
  end
  # devise_for :employees, path: 'dashboard/employees', skip: [:sessions]
  # as :employee do
  #   get 'login', to: 'devise/sessions#new', as: :new_app_account_session
  #   post 'login', to: 'devise/sessions#create', as: :app_account_session
  #   get 'logout', to: 'devise/sessions#destroy', as: :destroy_app_account_session
  #   root to: 'devise/sessions#new'
  # end

  devise_for :users, skip: [:sessions, :registrations]
  as :user do
    get '/events/:event_code/sign_in', to: 'users/sessions#new', as: :new_user_session
    post '/events/:event_code/sign_in', to: 'users/sessions#create', as: :user_session
    get 'sign_out', to: 'users/sessions#destroy', as: :destroy_user_session

    get 'users/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get '/events/:event_code/sign_up', to: 'users/registrations#new', as: :new_user_registration
    get 'users/edit', to: 'users/registrations#edit', as: :edit_user_registration
    patch 'users', to: 'users/registrations#update', as: :user_registration_patch
    put 'users', to: 'users/registrations#update', as: :user_registration_put
    delete 'users', to: 'users/registrations#destroy', as: :user_registration_delete
    post '/events/:event_code/users', to: 'users/registrations#create', as: :user_registration
  end
  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # %w( 404 422 500 503 ).each do |code|
  #   match code, to: "errors#show", code: code
  # end
  get '/unauthorized', to: "errors#unauthorized"
  mount ActionCable.server => '/cable'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'main'
  before_action :authenticate_user!, except: [:welcome, :find_event, :forgot_password, :reset_password, :about_us, :contact_us]
  before_action :fetch_reaction, except: [:welcome, :find_event, :profile, :update_profile, :forgot_password, :reset_password, :about_us, :contact_us, :disabled]
  before_action -> { check_event_code params[:event_code] }, except: [:welcome, :forgot_password, :reset_password, :about_us, :contact_us]

  def index
    render_404 if @event.nil?

    GuestList.create_guest_list(current_user, @event)
    @guest = GuestList.invitation(current_user, @event)
    if @event.disable_main_event?
      redirect_to disabled_path(event_code: @event.event_code)
    elsif @guest.pending?
      redirect_to thank_you_path(event_code: @event.event_code)
    elsif @guest.denied?
      redirect_to denied_path(event_code: @event.event_code)
    end
  end

  def thank_you
    render_404 if @event.nil?

    @guest = GuestList.invitation(current_user, @event)
    if @guest.approved?
      redirect_to home_path(event_code: @event.event_code)
    elsif @guest.denied?
      redirect_to denied_path(event_code: @event.event_code)
    end
  end

  def denied
    render_404 if @event.nil?

    @guest = GuestList.invitation(current_user, @event)
    if @guest.approved?
      redirect_to home_path(event_code: @event.event_code)
    elsif @guest.pending?
      redirect_to thank_you_path(event_code: @event.event_code)
    end
  end

  def disabled
    render_404 if @event.nil?
  end

  def welcome
    render layout: "application"
  end

  def find_event
    if @event.nil?
      flash.now[:alert] = 'Invalid Event Code!'
      render :welcome, layout: "application"
    elsif @event.queued?
      flash.now[:alert] = 'Event not yet started!'
      render :welcome, layout: "application"
    elsif @event.done?
      flash.now[:alert] = 'Event already done!'
      render :welcome, layout: "application"
    elsif current_user.nil?
      redirect_to new_user_registration_path(event_code: @event.event_code)
    else
      # if @event.has_expo?
      #   redirect_to expo_path(event_code: @event.event_code)
      # else
      #   redirect_to home_path(event_code: @event.event_code)
      # end
      redirect_to home_path(event_code: @event.event_code)
    end
  end

  def profile
    @user = @current_user
  end

  def update_profile
    @user = @current_user
    if @user.update_attributes user_params
      redirect_to profile_path(event_code: @event.event_code), notice: "Profile updated successfully!"
    else
      render :profile
    end
  end

  def forgot_password
    @user = User.new
    render layout: "application"
  end

  def reset_password
    @user = User.find_by(email: params[:user][:email])
    if @user.nil?
      @user = User.new
      flash.now[:alert] = 'Invalid email'
      render :forgot_password, layout: "application"
    else
      @user = @user.generate_temporary_password
      if @user.save
        redirect_to root_path, notice: "#{@user.full_name} reset password successfully!"
      else
        @user = User.new
        render :forgot_password, layout: "application"
      end
    end
  end

  def about_us
    render layout: "application"
  end

  def contact_us
    render layout: "application"
  end

  private

  def user_params
    added_attrs = [:email, :password, :password_confirmation, :contact_number,
      :full_name, :member_id, :member_type, :affiliation, :abo_number, :aes_number,
      :company, :id_number, :distributor_number, :employee_number, :mailing_address,
      :member_company, :upline, :who_invited_you, :abo_type, :distributor_type]
    params.require(:user).permit(added_attrs)
  end

  def fetch_reaction
    @reaction = current_user.reactions.first || current_user.reactions.new
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
<section class="single-page-layout">
   <div class="container">
      <div class="row text-center py-5 justify-content-center">
         <div class="col-12 col-md-9">
            <h1>ABOUT US</h1>
            <p>
              WE MAKE EVENTS - live and virtual - HAPPEN. <br/> <br/>

              Our thrust is to generate ideas, produce event materials, videos, and content for our clients' needs and demands as we keep abreast of the industry's latest innovations.<br/> <br/>

              We are a team of skilled and experienced events management professionals. Passionate and dedicated to what we do, we make every event fun-filled, exciting, and remarkable.<br/> <br/>

              In each and every service that we take, we aim to bring your content to a world of creativity that would transcend beyond your purpose. Our goal is to make unimaginable things happen for you.<br/> <br/>
            </p>
         </div>
      </div>
   </div>
</section>

app/views/home/contact_us.html.erb
<section class="single-page-layout">
   <div class="container">
      <div class="row text-center py-5 justify-content-center">
         <div class="col-12 col-md-9">
            <h1>CONTACT US</h1>
            <p>
               <!-- This page is still under construction. -->
            </p>
            <div class="connect-with-us">
               <div class="content">
                  <p>Connect With us:</p>
                  <p class="mx-3">
                     For support or any questions
                     <br />
                     Email us at
                     <a href="mailto:quiplist.events@gmail.com">
                     quiplist.events@gmail.com
                     </a>
                  </p>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>

app/views/home/denied.html.erb
<div class="chat-live-wrapper denied" style="<%= @event.main_background? ? "background-image: url(\'#{@event.main_background.url}\')" : "" %>">
  <div class="container px-5 py-3">
      <div class="row">
            <div class="col-12">
              <div class="denied-wrapper">
                <h1 style="color: <%= @event.main_mouse_out %>;">Denied!</h1>
                <p class="lead">Sorry, you've been denied from entering this event.</p>
              </div>
            </div>
      </div>
  </div>
</div>

app/views/home/disabled.html.erb
<div class="chat-live-wrapper denied" style="<%= @event.main_background? ? "background-image: url(\'#{@event.main_background.url}\')" : "" %>">
  <div class="container px-5 py-3">
      <div class="row">
            <div class="col-12">
              <div class="denied-wrapper">
                <h1 style="color: <%= @event.main_mouse_out %>;">Sorry, the event has not started yet.</h1>
              </div>
            </div>
      </div>
  </div>
</div>

app/views/home/forgot_password.html.erb
<div class="chat-live-wrapper thankyou main-bg" style="">
  <div class="container px-5 py-3">
      <div class="row">
            <div class="col-12">
               <%= form_for @user, as: :user, url: reset_password_path, method: :post, html: { class: "row password-form-wrapper text-start" } do |f| %>
                  <%= render partial: "layouts/shared/error_messages", locals: { messages: @user.errors.full_messages } %>
                  <% if notice %>
                     <p class="alert alert-success"><%= notice %></p>
                  <% end %>
                  <% if alert %>
                     <p class="alert alert-danger"><%= alert %></p>
                  <% end %>
                  <div class="row px-0">
                    <div class="col">
                      <h4 class="text-start">Forgot Password?</h4>
                      <hr/>
                    </div>
                  </div>
                  <div class="mb-3 px-0">
                     <%= f.label :email %><br />
                     <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
                  </div>
                  <div class="actions text-center">
                        <%= f.submit "Reset Password", class: "btn btn-blue" %>
                  </div>
               <% end %>
            </div>
      </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="chat-live-wrapper main-bg">
  <div class="container-fluid px-3 py-5">
      <%= react_component("Live", {
        fbVideo: @event.fb_video?,
        ytVideo: @event.youtube_video?,
        noVideo: @event.no_video?,
        url: @event.stream_key,
        eventId: @event.id,
        currentUserId: @current_user.id,
        eventId: @event.id,
        like: @reaction.like?,
        heart: @reaction.heart?,
        happy: @reaction.happy?,
        sad: @reaction.sad?,
        wow: @reaction.wow?,
        angry: @reaction.angry?,
        dislike: @reaction.dislike?,
        clap: @reaction.clap?,
        eventDescription: @event.description,
        raffleId: @guest.raffle_number,
        countLike: Reaction.count_reactions(Reaction::LIKE, "User", @current_user.id, @event.id),
        countDislike: Reaction.count_reactions(Reaction::DISLIKE, "User", @current_user.id, @event.id),
        countClap: Reaction.count_reactions(Reaction::CLAP, "User", @current_user.id, @event.id),
        countLove: Reaction.count_reactions(Reaction::HEART, "User", @current_user.id, @event.id),
        countHaha: Reaction.count_reactions(Reaction::HAPPY, "User", @current_user.id, @event.id),
        countWow: Reaction.count_reactions(Reaction::WOW, "User", @current_user.id, @event.id),
        countSad: Reaction.count_reactions(Reaction::SAD, "User", @current_user.id, @event.id),
        countAngry: Reaction.count_reactions(Reaction::ANGRY, "User", @current_user.id, @event.id),
        hasBrochure: @event.has_brochure?
      })%>

  </div>
</div>

app/views/home/profile.html.erb
<div class="chat-live-wrapper thankyou main-bg">
  <div class="container px-5 py-3">
      <div class="row">
            <div class="col-12">
                <%= form_for @user, as: :user, url: update_profile_path(event_code: @event.event_code), method: :put, html: { class: "row profile-form-wrapper text-start", multipart: true } do |f| %>
                  <%= render partial: "layouts/shared/success_messages", locals: { messages: flash[:notice] } %>
                  <%= render partial: "layouts/shared/error_messages", locals: { messages: @user.errors.full_messages } %>
                  <div class="row px-0">
                    <div class="col">
                      <h4 class="text-start">My Profile</h4>
                      <hr/>
                    </div>
                  </div>
                  <div class="col-12">
                      <label for="full_name">Full Name <span class="required">*</span></label>
                      <%= f.text_field :full_name, autofocus: true, autocomplete: "email", class:"form-control"%>
                  </div>
                  <div class="col-12">
                    <label for="email">Email <span class="required">*</span></label>
                    <%= f.email_field :email, class: "form-control" %>
                  </div>
                  <% if @event.include_affiliation? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Affiliation
                          <% if @event.required_affiliation? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :affiliation, class: "form-control" %>
                    </div>
                  <% end %>
                  <% if @event.include_company? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Company
                          <% if @event.required_company? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :company, class: "form-control" %>
                    </div>
                  <% end %>
                  <% if @event.include_member_company? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Member Company
                          <% if @event.required_member_company? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :member_company, class: "form-control" %>
                    </div>
                  <% end %>

                  <% if @event.include_contact_number? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Contact Number
                          <% if @event.required_contact_number? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :contact_number, class: "form-control" %>
                    </div>
                  <% end %>
                  <% if @event.include_mailing_address? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Mailing Address
                          <% if @event.required_mailing_address? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :mailing_address, class: "form-control" %>
                    </div>
                  <% end %>
                  <% if @event.include_who_invited_you? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Who Invited You?
                          <% if @event.required_who_invited_you? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :who_invited_you, class: "form-control" %>
                    </div>
                  <% end %>
                  <% if @event.include_upline? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Upline
                          <% if @event.required_upline? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :upline, class: "form-control" %>
                    </div>
                  <% end %>

                  <% if @event.include_member_type? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Member Type
                          <% if @event.required_member_type? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <% if @event.with_guest_member_type %>
                          <%= f.select :member_type, User::MEMBER_TYPES_WITH_GUEST.invert, {}, { class: 'form-select' } %>
                        <% else %>
                          <%= f.select :member_type, User::MEMBER_TYPES.invert, {}, { class: 'form-select' } %>
                        <% end %>
                    </div>
                  <% end %>
                  <% if @event.include_member_id? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Member Id
                          <% if @event.required_member_id? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :member_id, class: "form-control" %>
                    </div>
                  <% end %>
                  <% if @event.include_abo_type? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          ABO Type
                          <% if @event.required_abo_type? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <% if @event.with_guest_abo_type %>
                          <%= f.select :abo_type, User::ABO_TYPES_WITH_GUEST.invert, {}, { class: 'form-select' } %>
                        <% else %>
                          <%= f.select :abo_type, User::ABO_TYPES.invert, {}, { class: 'form-select' } %>
                        <% end %>
                    </div>
                  <% end %>
                  <% if @event.include_abo_number? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          ABO Number
                          <% if @event.required_abo_number? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :abo_number, class: "form-control" %>
                    </div>
                  <% end %>
                  <% if @event.include_aes_number? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          AES Number
                          <% if @event.required_aes_number? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :aes_number, class: "form-control" %>
                    </div>
                  <% end %>
                  <% if @event.include_distributor_type? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Distributor Type
                          <% if @event.required_distributor_type? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <% if @event.with_guest_distributor_type %>
                          <%= f.select :distributor_type, User::DISTRIBUTOR_TYPES_WTIH_GUEST.invert, {}, { class: 'form-select' } %>
                        <% else %>
                          <%= f.select :distributor_type, User::DISTRIBUTOR_TYPES.invert, {}, { class: 'form-select' } %>
                        <% end %>
                    </div>
                  <% end %>
                  <% if @event.include_distributor_number? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Distributor Number
                          <% if @event.required_distributor_number? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :distributor_number, class: "form-control" %>
                    </div>
                  <% end %>
                  <% if @event.include_employee_number? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Employee Number
                          <% if @event.required_employee_number? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :employee_number, class: "form-control" %>
                    </div>
                  <% end %>
                  <% if @event.include_id_number? %>
                    <div class="col-12 col-md-6">
                        <label for="email">
                          Id Number
                          <% if @event.required_id_number? %>
                            <span class="required">*</span>
                          <% end %>
                        </label>
                        <%= f.text_field :id_number, class: "form-control" %>
                    </div>
                  <% end %>
                  <div class="py-3 text-center">
                      <%= submit_tag "Save", class: "btn btn-blue px-5" %>
                  </div>
                <% end %>
            </div>
      </div>
  </div>
</div>

app/views/home/thank_you.html.erb
<div class="chat-live-wrapper thankyou main-bg">
  <div class="container px-5 py-3">
      <div class="row">
            <div class="col-12">
              <div class="thankyou-wrapper">
                <h1 style="color: <%= @event.main_mouse_out %>;">Thank you for registering</h1>
                <br/>
                <p class="lead">The admin will check your login credentials before granting access.
                  <br/>
                  <br/>
                  Sign in
                  <% unless @event.start_date.nil? %>
                    on <%= date_formatter(@event.start_date) %>
                  <% end %>
                  <% unless @event.start_time.nil? %>
                   at <%= time_formatter(@event.start_time) %>
                  <% end %>
                  using the email address and password that you have registered to enjoy the show.
                </p>
              </div>
            </div>
      </div>
  </div>
</div>

app/views/home/welcome.html.erb
<div class="home">
   <section id="section1">
      <div id="sliderIndicators" class="carousel slide" data-bs-ride="carousel">
         <div class="carousel-inner">
            <div class="carousel-item active">
               <%#= image_tag "placeholder1.jpg", class: "d-block w-100", alt:"placeholder1" %>
               <%= image_tag "main_page_1.jpg", class: "d-block w-100", alt:"placeholder1" %>
            </div>
            <!-- <div class="carousel-item">
               <%#= image_tag "placeholder2.jpg", class: "d-block w-100", alt:"placeholder2" %>
            </div>
            <div class="carousel-item">
               <%#= image_tag "placeholder3.jpg", class: "d-block w-100", alt:"placeholder3" %>
            </div> -->
         </div>
      </div>
   </section>
   <section id="section2" class="blue-bg_home py-5">
      <div class="overlap_top-bg">
         <%= image_tag "top.png", class: "img-fluid", alt:"top" %>
      </div>
      <div class="container-fluid events-code__wrapper">
        <div class="row">
            <div class="col-12 text-center">
                <h1>Welcome!</h1>
            </div>
        </div>
         <div class="row event-box text-center">
            <div class="col col-lg-12">
               <% if alert %>
               <p class="alert alert-danger"><%= alert %></p>
               <% end %>
               <%= form_tag(find_event_path, { method: :get, class: "text-center"}) do %>
               <div class="mb-3">
                  <%= text_field_tag :event_code, nil, class: 'form-control mt-3 mb-2', id: "eventCode", placeholder: "Event Code" %>
                  <label for="eventCode">Please enter your unique code here. This code is exclusive and
                  can only be used once and during the event phase only.
                  Sharing this code may cost you to lose your event access.
                  </label>
               </div>
               <div class="row justify-content-end align-items-center mb-3">
                  <div class="col-9 text-start">
                     <!-- <div class="form-check px-0 align-items-center">
                        <input type="checkbox" id="terms">
                        <label class="form-check-label px-1" for="terms">
                        I agree to the Terms of Service
                        and Privacy Policy.
                        </label>
                     </div> -->
                  </div>
                  <div class="col-3 text-end">
                     <button type="submit" class="btn btn-event-code">Join</button>
                  </div>
               </div>
               <% end %>
            </div>
         </div>
      </div>
      <div class="overlap_bottom-bg"><%= image_tag "bottom.png", class: "img-fluid", alt:"bottom" %></div>
    </section>
</div>