config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  get 'errors/show'
  get 'errors/unauthorized'
  root to: 'home#welcome'
  get '/events/:event_code', to: 'home#index', as: :home
  get '/events/:event_code/thank_you', to: 'home#thank_you', as: :thank_you
  get '/events/:event_code/denied', to: 'home#denied', as: :denied
  get '/events/:event_code/disabled', to: 'home#disabled', as: :disabled
  get '/find_event', to: 'home#find_event', as: :find_event
  get '/profile', to: 'home#profile', as: :profile
  put '/profile', to: 'home#update_profile', as: :update_profile
  get '/forgot_password', to: 'home#forgot_password', as: :forgot_password
  post '/reset_password', to: 'home#reset_password', as: :reset_password
  get '/contact_us', to: 'home#contact_us', as: :contact_us
  get '/about_us', to: 'home#about_us', as: :about_us

  scope 'admins' do
    get '/forgot_password', to: 'admins#forgot_password', as: :admin_forgot_password
    post '/forgot_password', to: 'admins#reset_forgot_password', as: :admin_reset_password
    get '/dashboard', to: 'admins#dashboard', as: :admin_dashboard
    resources :events, except: [:new, :edit] do
      put :upload_brochure, to: 'events#upload_brochure', on: :member
      get :launch, to: 'events#launch', on: :member
      get :expo, to: 'events#expo', on: :member

      resources :guest_lists do
        post :set_status, on: :collection
        post :set_raffle_status, on: :collection
        get :reset_raffle_statuses, on: :collection
        get :download_csv, on: :collection
      end
      resources :raffles, except: [:index]
      resources :questionnaires, except: [:index] do
        get '/pinned/:answer_id', to: 'questionnaires#pinned', on: :member, as: :pinned_answer
      end
      resources :feed_backs, except: [:index] do
        get :download_csv, on: :member
      end
    end
    resources :admins do
      post :create_admin_events, on: :member
      delete :destroy_admin_events, on: :member
      put :reset_password, on: :member
      get :profile, on: :collection
      put :profile, to: 'admins#update_profile', on: :collection
      get :change_password, on: :collection
      put :change_password, to: 'admins#update_password', on: :collection
    end
    resources :users, except: [:new, :edit, :create, :update, :destroy] do
      put :reset_password, on: :member
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :reactions, only: [:create] do
        delete :destroy, on: :collection
      end
      resources :chats, only: [:index, :create]
      resources :announcements, only: [:index, :create, :update]
      get '/fetch_current_user', to: 'users#fetch_current_user', as: :fetch_current_user
      resources :events, only: [:show, :update]
      resources :raffles, only: [:index, :show, :update]
      resources :questionnaires, only: [:update]
      resources :guest_lists, only: [:index, :show]
      resources :answers, only: [:create]
      get '/fetch_current_event/:id', to: 'events#fetch_current_event', as: :fetch_current_event

      resources :game_scores, only: [:create, :index, :show, :update]
      resources :users, only: [:show]
      resources :ratings, only: [:index, :create]
    end
  end

  # devise_for :users, skip: [:sessions]
  # as :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  #   post 'sign_in', to: 'devise/sessions#create'
  #   get 'sign_out', to: 'devise/sessions#destroy'
  #   #root to: 'devise/sessions#new', as: 'authenticated_user_root'
  # end
  devise_for :admins, controllers: { sessions: 'admins/sessions' }, :skip => [:registrations]
    as :admin do
    get 'admins/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'admins/registrations#update', :as => 'admin_registration'
  end
  # devise_for :employees, path: 'dashboard/employees', skip: [:sessions]
  # as :employee do
  #   get 'login', to: 'devise/sessions#new', as: :new_app_account_session
  #   post 'login', to: 'devise/sessions#create', as: :app_account_session
  #   get 'logout', to: 'devise/sessions#destroy', as: :destroy_app_account_session
  #   root to: 'devise/sessions#new'
  # end

  devise_for :users, skip: [:sessions, :registrations]
  as :user do
    get '/events/:event_code/sign_in', to: 'users/sessions#new', as: :new_user_session
    post '/events/:event_code/sign_in', to: 'users/sessions#create', as: :user_session
    get 'sign_out', to: 'users/sessions#destroy', as: :destroy_user_session

    get 'users/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get '/events/:event_code/sign_up', to: 'users/registrations#new', as: :new_user_registration
    get 'users/edit', to: 'users/registrations#edit', as: :edit_user_registration
    patch 'users', to: 'users/registrations#update', as: :user_registration_patch
    put 'users', to: 'users/registrations#update', as: :user_registration_put
    delete 'users', to: 'users/registrations#destroy', as: :user_registration_delete
    post '/events/:event_code/users', to: 'users/registrations#create', as: :user_registration
  end
  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # %w( 404 422 500 503 ).each do |code|
  #   match code, to: "errors#show", code: code
  # end
  get '/unauthorized', to: "errors#unauthorized"
  mount ActionCable.server => '/cable'
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::ApplicationController

  before_action :doorkeeper_authorize!, only: [:fetch_current_event]
  load_and_authorize_resource :event, only: [:show]
  before_action :set_event, only: [:fetch_current_event, :update]

  def show
    render json: @event, include: [:chats, :announcements]
  end

  def update
    if @event.update event_params
        EventsChannel.broadcast_to(@event, ActiveModelSerializers::SerializableResource.new(@event).as_json)
    end
    render json: @event
  end

  def fetch_current_event
    render json: @event, serializer: EventMinimalSerializer
  end

  private

  def set_event
    @event = Event.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      render json: { errors: e.to_s }, status: :not_found
  end

  def event_params
    params.require(:event).permit(:disable_expo_games, :disable_main_event)
  end
end

app/controllers/events_controller.rb
  class EventsController < ApplicationController
  layout 'admin'

  before_action :authenticate_admin!
  before_action :fetch_reaction, only: [:launch]
  load_and_authorize_resource :event

  def index
    @events = Event.joins(:admin_events).where(admin_events: { admin: @current_user } ) if @current_user.admin?
    @events = @events.sorted
    @event = Event.new
  end

  def show
    @guest_lists = GuestList.where(event: @event)
    @guest_lists = @guest_lists.sorted

    @raffles = Raffle.where(event: @event)
    @raffles = @raffles.sorted

    @questionnaires = Questionnaire.where(event: @event)
    @questionnaires = @questionnaires.sorted

    @feed_backs = FeedBack.where(event: @event)
    @feed_backs = @feed_backs.sorted
  end

  def create
    if @event.save
      redirect_to event_path(@event), notice: "Event #{@event.title} added successfully!"
    else
      @events = Event.all
      @events = Event.joins(:admin_events).where(admin_events: { admin: @current_user } ) if @current_user.admin?
      @events = @events.sorted
      @isCreate = true
      render :index
    end
  end

  def update
    if @event.update_attributes event_params
      redirect_to event_path(@event), notice: "Event #{@event.title} updated successfully!"
    else
      @events = Event.all
      @events = Event.joins(:admin_events).where(admin_events: { admin: @current_user } ) if @current_user.admin?
      @events = @events.sorted
      @isUpdate = true
      render :index
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: "Event deleted successfully!"
  end

  def upload_brochure
    if @event.update_attributes upload_params
      redirect_to event_path(@event), notice: "brochure uploaded successfully!"
    else
      @guest_lists = GuestList.where(event: @event)
      @guest_lists = @guest_lists.sorted

      @raffles = Raffle.where(event: @event)
      @raffles = @raffles.sorted

      @questionnaires = Questionnaire.where(event: @event)
      @questionnaires = @questionnaires.sorted
      render :show
    end
  end

  # def set_raffle_status
  #   page = params[:page] || 1
  #   per_page = params[:per_page] || 10
  #   search = params[:search]
  #   @guest_lists = @event.guest_lists
  #   @guest_lists = @guest_lists.sorted.page(page).per(per_page)
  #   guest_list = GuestList.find(params[:guest_list_id])
  #   response = update_raffle_statuses([guest_list], raffle_status_params)
  #
  #   redirect_to events_path, notice: "Guest #{guest_list.user.full_name} updated successfully!"
  # end

  def launch
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :event_code,
      :start_date, :end_date, :start_time, :end_time, :event_type,
      :stream_type, :stream_key, :stream_video, :status, :session_background,
      :session_mouse_out, :session_mouse_over, :session_background_color,
      :main_background, :main_mouse_out, :main_mouse_over, :main_background_color,
      :include_abo_number, :required_abo_number, :include_aes_number, :required_aes_number,
      :include_affiliation, :required_affiliation, :include_company, :required_company,
      :include_contact_number, :required_contact_number, :include_distributor_number,
      :required_distributor_number, :include_employee_number, :required_employee_number,
      :include_id_number, :required_id_number, :include_mailing_address, :required_mailing_address,
      :include_member_company, :required_member_company, :include_member_id, :required_member_id,
      :include_member_type, :required_member_type, :include_upline, :required_upline, :include_who_invited_you,
      :required_who_invited_you, :include_abo_type, :include_distributor_type, :required_abo_type,
      :required_distributor_type, :with_guest_member_type, :with_guest_abo_type, :with_guest_distributor_type,
      :random_name_background, :random_name_background_color, :random_name_draw_mouse_out, :random_name_draw_mouse_over,
      :random_name_winner_mouse_out, :random_name_winner_mouse_over, :random_number_background, :random_number_background_color,
      :random_number_draw_mouse_out, :random_number_draw_mouse_over, :random_number_winner_mouse_out, :random_number_winner_mouse_over,
      :spin_a_wheel_background, :spin_a_wheel_background_color, :spin_a_wheel_draw_mouse_out, :spin_a_wheel_draw_mouse_over,
      :spin_a_wheel_winner_mouse_out, :spin_a_wheel_winner_mouse_over, :has_expo, :has_background_music, :disable_expo_games,
      :background_music, :disable_main_event, :random_name_winner_background_color, :random_number_winner_background_color,
      :spin_a_wheel_winner_background_color, :random_name_winner_font_color, :random_number_winner_font_color, :spin_a_wheel_winner_font_color,
      :random_name_font_color, :random_number_font_color, :spin_a_wheel_font_color
    )
  end

  def upload_params
    params.require(:event).permit(:brochure)
  end

  def winner_params
    params.require(:guest_list).permit(:raffle_status)
  end

  def fetch_reaction
    @reaction = current_admin.reactions.first || current_admin.reactions.new
  end
end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/shared/_form.html.erb
<div class="mb-3">
  <%= f.text_field :title, class: 'form-control', id: "title", placeholder: "Enter Event Title*" %>
</div>
<div class="mb-3">
  <%= f.text_area :description, rows: '4', class: 'form-control', placeholder:"Event Desctiption" %>
</div>
<div class="mb-3">
  <%= f.text_field :event_code, class: 'form-control', id: "event_code", placeholder: "Enter Event Code*" %>
</div>
<div class="mb-3">
  <div class="row">
    <div class="col col-lg-6">
      <label for="startDate">Start Date</label>
      <%= f.date_field :start_date, class: 'form-control' %>
    </div>
    <div class="col col-lg-6">
      <label for="endDate">End Date</label>
      <%= f.date_field :end_date, class: 'form-control' %>
    </div>
  </div>
</div>
<div class="mb-3">
  <div class="row">
    <div class="col col-lg-6">
      <label for="startTime">Start Time</label>
      <%= f.time_field :start_time, class: 'form-control' %>
    </div>
    <div class="col col-lg-6">
      <label for="endTime">End Time</label>
      <%= f.time_field :end_time, class: 'form-control' %>
    </div>
  </div>
</div>
<div class="mb-3">
  <label class="w-100" for="eventtype">Event Type<span class="required">*</span></label>
  <div class="form-check form-check-inline">
    <%= f.radio_button :event_type, Event::PUBLIC, class: "form-check-input" %>
    <label class="form-check-label mx-1" for="public">Public</label>
  </div>
  <div class="form-check form-check-inline">
    <%= f.radio_button :event_type, Event::PRIVATE, class: "form-check-input" %>
    <label class="form-check-label mx-1" for="private">Private</label>
  </div>
</div>
<div class="mb-3">
  <label for="streamType">Stream Type <span class="required">*</span></label>
  <div class="row stream">
    <div class="col col-lg-6">
      <%= f.select :stream_type, Event::STREAM_TYPES.invert, {}, { class: "form-select stream_type_#{id}", onchange: "streamValueTypeChange(#{id})" } %>
    </div>
    <div class="col col-lg-6 uploadVideo_<%= id %>">
      <input type="file" id="event" accept="video/*" name="event[stream_video]">
    </div>
    <div class="col col-lg-6 streamVideo_<%= id %>">
      <%= f.text_field :stream_key, class: 'form-control', id: "stream_key", placeholder: "Stream Key/Url" %>
    </div>
  </div>
</div>

app/views/events/shared/_guest_lists_tab.html.erb
<div class="tab-pane fade show active" id="nav-users" role="tabpanel" aria-labelledby="nav-users-tab">
  <table id="event_id_guest_list" class="table guest-data-table hover">
    <thead>
      <tr>
        <th>Status</th>
        <th>Full Name</th>
        <th>Email</th>
        <% if @event.include_company %>
          <th>Company</th>
        <% end %>
        <% if @event.include_affiliation %>
          <th>Affiliation</th>
        <% end %>
        <% if @event.include_member_company %>
          <th>Member Company</th>
        <% end %>
        <% if @event.include_member_type %>
          <th>Member Type</th>
        <% end %>
        <% if @event.include_abo_type %>
          <th>ABO Type</th>
        <% end %>
        <% if @event.include_distributor_type %>
          <th>Distributor Type</th>
        <% end %>
        <% if @event.include_member_id %>
          <th>Member Id</th>
        <% end %>
        <% if @event.include_employee_number %>
          <th>Employee Number</th>
        <% end %>
        <% if @event.include_id_number %>
          <th>Id Number</th>
        <% end %>
        <% if @event.include_abo_number %>
          <th>ABO Number</th>
        <% end %>
        <% if @event.include_aes_number %>
          <th>AES Number</th>
        <% end %>
        <% if @event.include_distributor_number %>
          <th>Distributor Number</th>
        <% end %>
        <% if @event.include_mailing_address %>
          <th>Mailing Address</th>
        <% end %>
        <% if @event.include_contact_number %>
          <th>Contact Number</th>
        <% end %>
        <% if @event.include_who_invited_you %>
          <th>Who invited you?</th>
        <% end %>
        <% if @event.include_upline %>
          <th>Upline</th>
        <% end %>

        <th>
          Raffle status
          <% if can? :update, GuestList %>
            <%= link_to reset_raffle_statuses_event_guest_lists_path(@event), class: "text-xl-start text-primary" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-clockwise" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z"/>
                <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z"/>
              </svg>
            <% end %>
          <% end %>
        </th>
        <th>Approved by:</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @guest_lists.each do |guest_list| %>
        <tr>
          <td><%= guest_list.status_name %></td>
          <td><%= guest_list.user.full_name %></td>
          <td><%= guest_list.user.email %></td>
          <% if @event.include_company %>
            <td><%= guest_list.user.company %></td>
          <% end %>
          <% if @event.include_affiliation %>
            <td><%= guest_list.user.affiliation %></td>
          <% end %>
          <% if @event.include_member_company %>
            <td><%= guest_list.user.member_company %></td>
          <% end %>
          <% if @event.include_member_type %>
            <td><%= guest_list.user.member_name %></td>
          <% end %>
          <% if @event.include_abo_type %>
            <td><%= guest_list.user.abo_type_name %></td>
          <% end %>
          <% if @event.include_distributor_type %>
            <td><%= guest_list.user.distributor_type_name %></td>
          <% end %>
          <% if @event.include_member_id %>
            <td><%= guest_list.user.member_id %></td>
          <% end %>
          <% if @event.include_employee_number %>
            <td><%= guest_list.user.employee_number %></td>
          <% end %>
          <% if @event.include_id_number %>
            <td><%= guest_list.user.id_number %></td>
          <% end %>
          <% if @event.include_abo_number %>
            <td><%= guest_list.user.abo_number %></td>
          <% end %>
          <% if @event.include_aes_number %>
            <td><%= guest_list.user.aes_number %></td>
          <% end %>
          <% if @event.include_distributor_number %>
            <td><%= guest_list.user.distributor_number %></td>
          <% end %>
          <% if @event.include_mailing_address %>
            <td><%= guest_list.user.mailing_address %></td>
          <% end %>
          <% if @event.include_contact_number %>
            <td><%= guest_list.user.contact_number %></td>
          <% end %>
          <% if @event.include_who_invited_you %>
            <td><%= guest_list.user.who_invited_you %></td>
          <% end %>
          <% if @event.include_upline %>
            <td><%= guest_list.user.upline %></td>
          <% end %>
          <td>
            <%= form_for guest_list, as: :guest_list, url: set_raffle_status_event_guest_lists_path(@event, guest_list_id: guest_list.id), method: :post, html: { class: "" } do |f| %>
              <%= f.select :raffle_status, GuestList::RAFFLE_STATUSES.invert, {}, { class: 'form-select', onchange: "form.submit()", disabled: (cannot? :update, GuestList) } %>
            <% end %>
          </td>
          <td><%= guest_list.approver&.full_name %></td>
          <td>
            <%= form_for guest_list, as: :guest_list, url: set_status_event_guest_lists_path(@event, guest_list_id: guest_list.id), method: :post, html: { class: "" } do |f| %>
              <%= f.select :status, GuestList::STATUSES.invert, {}, { class: 'form-select', onchange: "form.submit()", disabled: (cannot? :update, GuestList) } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= link_to "Export CSV", download_csv_event_guest_lists_path(@event, format: "csv"), class: "btn-dowload-csv" %>
  </div>
</div>

app/views/events/shared/_raffles_tab.html.erb
<div class="tab-pane fade show" id="nav-raffles" role="tabpanel" aria-labelledby="nav-raffles-tab">
  <% if (can? :create, Raffle) %>
    <%= link_to "Add raffle", new_event_raffle_path(event_id: @event.id), class: 'btn btn-blue mt-2' %>
  <% end %>
  <table id="event_id_guest_list" class="table raffle-data-table hover">
    <thead>
      <tr>
        <th>Raffle Type</th>
        <th>Raffle Prize</th>
        <th>Winner</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @raffles.each do |raffle| %>
        <tr>
          <td><%= raffle.raffle_type_name %></td>
          <td><%= raffle.prize %></td>
          <td><%= raffle.winner&.user&.full_name %></td>
          <td><%= raffle.status_name %></td>
          <td class="actions text-center">
            <% if can? :show, Raffle %>
              <%= link_to "Show", event_raffle_path(event_id: @event.id, id: raffle.id), class: 'btn btn-view', target:"_blank" %>
            <% end %>
            <% if can? :update, Raffle %>
              <%= link_to "Edit", edit_event_raffle_path(event_id: @event.id, id: raffle.id), class: 'btn btn-edit' %>
            <% end %>
            <% if (can? :destroy, Raffle) %>
              <a class="btn btn-remove" href="#" data-bs-toggle="modal" data-bs-target="#delete-modal-id-<%= raffle.id %>">Delete</a>
              <%= render partial: "layouts/shared/delete_modal", locals: { index_id: "#{raffle.id}", m_name: "Raffle", name: raffle.raffle_type_name, path: event_raffle_path(event_id: @event.id, id: raffle.id) } %>
            <% end %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>